# Generated by Django 5.1 on 2025-06-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='loan_approve',
            new_name='is_approved',
        ),
    ]
